//! Generates JSON Schema and CDDL definitions for the canonical types of
//! `tpt-primitives` into `schemas/`.
//!
//! Usage:
//!
//! ```text
//! schema-gen            # regenerate schemas/ from the Rust types
//! schema-gen --check    # fail with a diff if schemas/ has drifted
//! ```
//!
//! CI runs `--check` so a PR that changes a canonical type without
//! regenerating its schemas cannot merge.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

use tpt_primitives::schema::{CDDL_PRELUDE, entries};

const JSON_HEADER: &str = r#"{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://tpt.example/schemas/tpt-primitives.schema.json",
  "title": "TPT Primitives canonical types",
  "description": "Payload schemas for the canonical objects of tpt-primitives. On the wire each payload is wrapped in the schema-version envelope [\"tpt-canonical\", version, payload] (see docs/decisions/0001-canonical-encoding-and-identity.md).",
  "$defs": {
"#;

const CDDL_HEADER: &str = r#"; TPT Primitives canonical types — CDDL definitions.
; Generated by schema-gen; do not edit by hand.
; Wire form: every payload below is wrapped in
;   tpt-envelope<V> = ["tpt-canonical", version: uint, payload: V]
"#;

fn main() {
    let check = std::env::args().any(|arg| arg == "--check");
    if let Err(error) = run(check) {
        eprintln!("schema-gen: {error}");
        std::process::exit(1);
    }
}

fn run(check: bool) -> Result<(), String> {
    let out_dir = repo_root()?.join("schemas");
    let json_path = out_dir.join("tpt-primitives.schema.json");
    let cddl_path = out_dir.join("tpt-primitives.cddl");

    let json = render_json()?;
    let cddl = render_cddl();

    if check {
        let mut drifted = false;
        for (path, expected) in [(&json_path, json.as_str()), (&cddl_path, cddl.as_str())] {
            match fs::read_to_string(path) {
                Ok(actual) if actual == expected => {
                    println!("ok  {}", display(path));
                }
                Ok(_) => {
                    eprintln!("drift: {} does not match the current types", display(path));
                    drifted = true;
                }
                Err(e) => {
                    eprintln!("missing: {} ({e})", display(path));
                    drifted = true;
                }
            }
        }
        if drifted {
            return Err("schemas have drifted; run `cargo run -p schema-gen` and commit".into());
        }
        println!("schemas are up to date");
        return Ok(());
    }

    fs::create_dir_all(&out_dir).map_err(|e| format!("create {}: {e}", display(&out_dir)))?;
    fs::write(&json_path, &json).map_err(|e| format!("write {}: {e}", display(&json_path)))?;
    fs::write(&cddl_path, &cddl).map_err(|e| format!("write {}: {e}", display(&cddl_path)))?;
    println!("wrote {} ({} types)", display(&json_path), entry_count());
    println!("wrote {}", display(&cddl_path));
    Ok(())
}

fn entry_count() -> usize {
    entries().len()
}

/// One JSON Schema file with every registered type under `$defs`.
fn render_json() -> Result<String, String> {
    let mut out = String::new();
    out.push_str(JSON_HEADER);
    for (i, entry) in entries().iter().enumerate() {
        let schema = (entry.json_schema)();
        let value =
            serde_json::to_value(&schema).map_err(|e| format!("schema {}: {e}", entry.name))?;
        let pretty = serde_json::to_string_pretty(&value)
            .map_err(|e| format!("schema {}: {e}", entry.name))?;
        let indented = indent(&pretty, "    ");
        let _ = write!(out, "    \"{}\": {}", entry.name, indented);
        if i + 1 < entry_count() {
            out.push(',');
        }
        out.push('\n');
    }
    out.push_str("  }\n}\n");
    Ok(out)
}

/// One CDDL file: prelude followed by per-type notes.
fn render_cddl() -> String {
    let mut out = String::new();
    out.push_str(CDDL_HEADER);
    out.push('\n');
    out.push_str(CDDL_PRELUDE);
    out.push('\n');
    for entry in entries() {
        let _ = writeln!(out, "; --- {} ---", entry.name);
        out.push_str(entry.cddl);
        out.push('\n');
    }
    out
}

/// Indent every line after the first (the first line lands after `"name": `).
fn indent(text: &str, prefix: &str) -> String {
    let mut lines = text.lines();
    let mut out = String::new();
    if let Some(first) = lines.next() {
        out.push_str(first);
    }
    for line in lines {
        out.push('\n');
        out.push_str(prefix);
        out.push_str(line);
    }
    out
}

fn display(path: &Path) -> String {
    path.display().to_string()
}

/// The repository root: the parent of this crate (`crates/schema-gen`).
fn repo_root() -> Result<PathBuf, String> {
    let mut dir = std::env::current_dir().map_err(|e| format!("current dir: {e}"))?;
    loop {
        if dir.join("Cargo.toml").exists() && dir.join("crates").exists() {
            return Ok(dir);
        }
        if !dir.pop() {
            return Err("could not locate the repository root".into());
        }
    }
}
